"
I represent Fortran If (Logical) statement
"
Class {
	#name : #FASTFortranStatementIfLogical,
	#superclass : #FASTFortranEntity,
	#traits : 'FASTFortranTFortranExecutableStatement',
	#classTraits : 'FASTFortranTFortranExecutableStatement classTrait',
	#category : #'FAST-Fortran-Model-Entities'
}

{ #category : #meta }
FASTFortranStatementIfLogical class >> annotation [

	<FMClass: #StatementIfLogical super: #FASTFortranEntity>
	<package: #'FAST-Fortran-Model'>
	<generated>
	^self
]
