"
I am a fortran not executable statement (I specify attributes, such as type and size; determine arrangement or order; define initial data values; specify editing instructions; define statement functions; classify program units; and define entry points. In general, I am are completed before execution of the first executable statement)
"
Trait {
	#name : #FASTFortranTFortranNotExecutableStatement,
	#category : #'FAST-Fortran-Model-Traits'
}

{ #category : #meta }
FASTFortranTFortranNotExecutableStatement classSide >> annotation [

	<FMClass: #TFortranNotExecutableStatement super: #Object>
	<package: #'FAST-Fortran-Model'>
	<generated>
	^self
]
