"
I represent Fortran Go To (Unconditional) statement
"
Class {
	#name : #FASTFortranStatementGoToUnconditional,
	#superclass : #FASTFortranEntity,
	#traits : 'FASTFortranTFortranExecutableStatement',
	#classTraits : 'FASTFortranTFortranExecutableStatement classTrait',
	#category : #'FAST-Fortran-Model-Entities'
}

{ #category : #meta }
FASTFortranStatementGoToUnconditional class >> annotation [

	<FMClass: #StatementGoToUnconditional super: #FASTFortranEntity>
	<package: #'FAST-Fortran-Model'>
	<generated>
	^self
]
