"
I represent Fortran Intrinsic statement
"
Class {
	#name : #FASTFortranStatementIntrinsic,
	#superclass : #FASTFortranEntity,
	#traits : 'FASTFortranTFortranNotExecutableStatement',
	#classTraits : 'FASTFortranTFortranNotExecutableStatement classTrait',
	#category : #'FAST-Fortran-Model-Entities'
}

{ #category : #meta }
FASTFortranStatementIntrinsic class >> annotation [

	<FMClass: #StatementIntrinsic super: #FASTFortranEntity>
	<package: #'FAST-Fortran-Model'>
	<generated>
	^self
]
