"
I represent Fortran Close statement
"
Class {
	#name : #FASTFortranStatementClose,
	#superclass : #FASTFortranEntity,
	#traits : 'FASTFortranTFortranExecutableStatement',
	#classTraits : 'FASTFortranTFortranExecutableStatement classTrait',
	#category : #'FAST-Fortran-Model-Entities'
}

{ #category : #meta }
FASTFortranStatementClose class >> annotation [

	<FMClass: #StatementClose super: #FASTFortranEntity>
	<package: #'FAST-Fortran-Model'>
	<generated>
	^self
]
