"
I represent ""Non-standard"" or ""Extension"" feature which go beyond versions compatible with the ANSI X3.9-1978 FORTRAN standard and the corresponding International Organization for Standardization (ISO) 1539-1980, FIPS 69-1, BS 6832, and MIL-STD-1753 ( Floating-point arithmetic for both compilers is based on IEEE standard 754-1985, and international standard IEC 60559:1989); on SPARC platforms, both compilers provide support for the optimization-exploiting features of SPARC V8, and SPARC V9, including the UltraSPARC(TM) implementation. These features are defined in the SPARC Architecture Manuals, Version 8 (ISBN 0-13-825001-4), and Version 9 (ISBN 0-13-099227-5), published by Prentice-Hall for SPARC International.
"
Trait {
	#name : #FASTFortranTFortranNotStandardFeatures,
	#category : #'FAST-Fortran-Model-Traits'
}

{ #category : #meta }
FASTFortranTFortranNotStandardFeatures classSide >> annotation [

	<FMClass: #TFortranNotStandardFeatures super: #Object>
	<package: #'FAST-Fortran-Model'>
	<generated>
	^self
]
