"
I represent Fortran If (Arithmetic) statement
"
Class {
	#name : #FASTFortranStatementIfArithmetic,
	#superclass : #FASTFortranEntity,
	#traits : 'FASTFortranTFortranExecutableStatement',
	#classTraits : 'FASTFortranTFortranExecutableStatement classTrait',
	#category : #'FAST-Fortran-Model-Entities'
}

{ #category : #meta }
FASTFortranStatementIfArithmetic class >> annotation [

	<FMClass: #StatementIfArithmetic super: #FASTFortranEntity>
	<package: #'FAST-Fortran-Model'>
	<generated>
	^self
]
