"
I represent Fortran Go To (Computed) statement
"
Class {
	#name : #FASTFortranStatementGoToComputed,
	#superclass : #FASTFortranEntity,
	#traits : 'FASTFortranTFortranExecutableStatement',
	#classTraits : 'FASTFortranTFortranExecutableStatement classTrait',
	#category : #'FAST-Fortran-Model-Entities'
}

{ #category : #meta }
FASTFortranStatementGoToComputed class >> annotation [

	<FMClass: #StatementGoToComputed super: #FASTFortranEntity>
	<package: #'FAST-Fortran-Model'>
	<generated>
	^self
]
