"
I represent Fortran If (BLock) statement
"
Class {
	#name : #FASTFortranStatementIfBlock,
	#superclass : #FASTFortranEntity,
	#traits : 'FASTFortranTFortranExecutableStatement',
	#classTraits : 'FASTFortranTFortranExecutableStatement classTrait',
	#category : #'FAST-Fortran-Model-Entities'
}

{ #category : #meta }
FASTFortranStatementIfBlock class >> annotation [

	<FMClass: #StatementIfBlock super: #FASTFortranEntity>
	<package: #'FAST-Fortran-Model'>
	<generated>
	^self
]
