"
An abstract superclass representing an expression node of a source code.
"
Class {
	#name : #FASTFortranArithmeticTypeExpression,
	#superclass : #FASTFortranEntity,
	#category : #'FAST-Fortran-Model-Entities'
}

{ #category : #meta }
FASTFortranArithmeticTypeExpression class >> annotation [

	<FMClass: #ArithmeticTypeExpression super: #FASTFortranEntity>
	<package: #'FAST-Fortran-Model'>
	<generated>
	^self
]
