"
I represent Fortran Pause statement
"
Class {
	#name : #FASTFortranStatementPause,
	#superclass : #FASTFortranEntity,
	#traits : 'FASTFortranTFortranExecutableStatement',
	#classTraits : 'FASTFortranTFortranExecutableStatement classTrait',
	#category : #'FAST-Fortran-Model-Entities'
}

{ #category : #meta }
FASTFortranStatementPause class >> annotation [

	<FMClass: #StatementPause super: #FASTFortranEntity>
	<package: #'FAST-Fortran-Model'>
	<generated>
	^self
]
