"
I represent Fortran Print statement
"
Class {
	#name : #FASTFortranStatementPrint,
	#superclass : #FASTFortranEntity,
	#traits : 'FASTFortranTFortranExecutableStatement',
	#classTraits : 'FASTFortranTFortranExecutableStatement classTrait',
	#category : #'FAST-Fortran-Model-Entities'
}

{ #category : #meta }
FASTFortranStatementPrint class >> annotation [

	<FMClass: #StatementPrint super: #FASTFortranEntity>
	<package: #'FAST-Fortran-Model'>
	<generated>
	^self
]
