"
I represent Fortran Assign statement
"
Class {
	#name : #FASTFortranStatementAssign,
	#superclass : #FASTFortranEntity,
	#traits : 'FASTFortranTFortranExecutableStatement',
	#classTraits : 'FASTFortranTFortranExecutableStatement classTrait',
	#category : #'FAST-Fortran-Model-Entities'
}

{ #category : #meta }
FASTFortranStatementAssign class >> annotation [

	<FMClass: #StatementAssign super: #FASTFortranEntity>
	<package: #'FAST-Fortran-Model'>
	<generated>
	^self
]
