"
I represent Fortran Go To( Assigned) statement
"
Class {
	#name : #FASTFortranStatementGoToAssigned,
	#superclass : #FASTFortranEntity,
	#traits : 'FASTFortranTFortranExecutableStatement',
	#classTraits : 'FASTFortranTFortranExecutableStatement classTrait',
	#category : #'FAST-Fortran-Model-Entities'
}

{ #category : #meta }
FASTFortranStatementGoToAssigned class >> annotation [

	<FMClass: #StatementGoToAssigned super: #FASTFortranEntity>
	<package: #'FAST-Fortran-Model'>
	<generated>
	^self
]
